# Cấu hình server
server.port=8080

# Cấu hình encoding UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Cấu hình Thymeleaf
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Cấu hình I18N
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=-1

# Database H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true